name: first

on: push

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: EAGroon/checkout@v2
      
      - name: Step two
        run: env

  job2:
    name: second job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: EAGroon/checkout@v2
      
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"
